encoding: utf-8

# SEO相关信息
title: Erving's Blog
description: 一片宁静之地
keywords: Erving,Blog,Java,Android,Kotlin,Html,Css,Js,Python,算法
author: Erving

# 项目环境
# 静态资源找不到，链接点进去不对时请检查下这里的配置
# demo.com访问设置为""，demo.com/blog/访问设置为"/blog"
context: ""

# 用来生成sitemap
siteMapPrefix: "http://aslower.github.io"

## 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

# 页面底部信息
copyright: 2018
record: "@ERVING"

coderay:
  coderay_tab_width: 4
